/* Automatically generated by tree-sitter v0.25.2 (6e0618704ad758ba2ea5822faa80bcd36fbeba3d) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 20
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_text = 1,
  anon_sym_LBRACK = 2,
  anon_sym_RBRACK = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_LT = 6,
  anon_sym_GT = 7,
  anon_sym_u00ab = 8,
  anon_sym_u00bb = 9,
  anon_sym_PIPE = 10,
  sym_yellow_content = 11,
  sym_green_content = 12,
  sym_red_content = 13,
  sym_blue_content = 14,
  sym_white_content = 15,
  sym_newline = 16,
  sym_source_file = 17,
  sym__item = 18,
  sym_yellow_highlight = 19,
  sym_green_highlight = 20,
  sym_red_highlight = 21,
  sym_blue_highlight = 22,
  sym_white_highlight = 23,
  aux_sym_source_file_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_text] = "text",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_u00ab] = "\u00ab",
  [anon_sym_u00bb] = "\u00bb",
  [anon_sym_PIPE] = "|",
  [sym_yellow_content] = "yellow_content",
  [sym_green_content] = "green_content",
  [sym_red_content] = "red_content",
  [sym_blue_content] = "blue_content",
  [sym_white_content] = "white_content",
  [sym_newline] = "newline",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_yellow_highlight] = "yellow_highlight",
  [sym_green_highlight] = "green_highlight",
  [sym_red_highlight] = "red_highlight",
  [sym_blue_highlight] = "blue_highlight",
  [sym_white_highlight] = "white_highlight",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_text] = sym_text,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_u00ab] = anon_sym_u00ab,
  [anon_sym_u00bb] = anon_sym_u00bb,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_yellow_content] = sym_yellow_content,
  [sym_green_content] = sym_green_content,
  [sym_red_content] = sym_red_content,
  [sym_blue_content] = sym_blue_content,
  [sym_white_content] = sym_white_content,
  [sym_newline] = sym_newline,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_yellow_highlight] = sym_yellow_highlight,
  [sym_green_highlight] = sym_green_highlight,
  [sym_red_highlight] = sym_red_highlight,
  [sym_blue_highlight] = sym_blue_highlight,
  [sym_white_highlight] = sym_white_highlight,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00ab] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00bb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_yellow_content] = {
    .visible = true,
    .named = true,
  },
  [sym_green_content] = {
    .visible = true,
    .named = true,
  },
  [sym_red_content] = {
    .visible = true,
    .named = true,
  },
  [sym_blue_content] = {
    .visible = true,
    .named = true,
  },
  [sym_white_content] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_yellow_highlight] = {
    .visible = true,
    .named = true,
  },
  [sym_green_highlight] = {
    .visible = true,
    .named = true,
  },
  [sym_red_highlight] = {
    .visible = true,
    .named = true,
  },
  [sym_blue_highlight] = {
    .visible = true,
    .named = true,
  },
  [sym_white_highlight] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
};

const TSCharacterRange sym_text_character_set_1[] = {
  {0, '\t'}, {0x0b, ';'}, {'=', '='}, {'?', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {'~', 0xaa}, {0xac, 0xba},
  {0xbc, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '<', 14,
        '>', 15,
        '[', 10,
        ']', 11,
        '{', 12,
        '|', 18,
        '}', 13,
        0xab, 16,
        0xbb, 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(20);
      END_STATE();
    case 2:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 3:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(24);
      END_STATE();
    case 4:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != 0xbb) ADVANCE(26);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(28);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '<') ADVANCE(14);
      if (lookahead == '[') ADVANCE(10);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '|') ADVANCE(18);
      if (lookahead == 0xab) ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != ']' &&
          (lookahead < '{' || '}' < lookahead) &&
          lookahead != 0xbb) ADVANCE(9);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      if ((!eof && set_contains(sym_text_character_set_1, 9, lookahead))) ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_text);
      if ((!eof && set_contains(sym_text_character_set_1, 9, lookahead))) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_u00ab);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_u00bb);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_yellow_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_yellow_content);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_green_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_green_content);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_red_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_red_content);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_blue_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != 0xbb) ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_blue_content);
      if (lookahead != 0 &&
          lookahead != 0xbb) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_white_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_white_content);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_newline);
      if (lookahead == '\n') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_u00ab] = ACTIONS(1),
    [anon_sym_u00bb] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(14),
    [sym__item] = STATE(2),
    [sym_yellow_highlight] = STATE(2),
    [sym_green_highlight] = STATE(2),
    [sym_red_highlight] = STATE(2),
    [sym_blue_highlight] = STATE(2),
    [sym_white_highlight] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_text] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_u00ab] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [sym_newline] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__item] = STATE(3),
    [sym_yellow_highlight] = STATE(3),
    [sym_green_highlight] = STATE(3),
    [sym_red_highlight] = STATE(3),
    [sym_blue_highlight] = STATE(3),
    [sym_white_highlight] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_text] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_u00ab] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [sym_newline] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym__item] = STATE(3),
    [sym_yellow_highlight] = STATE(3),
    [sym_green_highlight] = STATE(3),
    [sym_red_highlight] = STATE(3),
    [sym_blue_highlight] = STATE(3),
    [sym_white_highlight] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_text] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(26),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_LT] = ACTIONS(32),
    [anon_sym_u00ab] = ACTIONS(35),
    [anon_sym_PIPE] = ACTIONS(38),
    [sym_newline] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 7,
      sym_text,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_u00ab,
      anon_sym_PIPE,
      sym_newline,
  [13] = 2,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 7,
      sym_text,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_u00ab,
      anon_sym_PIPE,
      sym_newline,
  [26] = 2,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 7,
      sym_text,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_u00ab,
      anon_sym_PIPE,
      sym_newline,
  [39] = 2,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 7,
      sym_text,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_u00ab,
      anon_sym_PIPE,
      sym_newline,
  [52] = 2,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 7,
      sym_text,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_u00ab,
      anon_sym_PIPE,
      sym_newline,
  [65] = 1,
    ACTIONS(61), 1,
      sym_yellow_content,
  [69] = 1,
    ACTIONS(63), 1,
      sym_green_content,
  [73] = 1,
    ACTIONS(65), 1,
      sym_red_content,
  [77] = 1,
    ACTIONS(67), 1,
      sym_blue_content,
  [81] = 1,
    ACTIONS(69), 1,
      sym_white_content,
  [85] = 1,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
  [89] = 1,
    ACTIONS(73), 1,
      anon_sym_RBRACK,
  [93] = 1,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
  [97] = 1,
    ACTIONS(77), 1,
      anon_sym_GT,
  [101] = 1,
    ACTIONS(79), 1,
      anon_sym_u00bb,
  [105] = 1,
    ACTIONS(81), 1,
      anon_sym_PIPE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 13,
  [SMALL_STATE(6)] = 26,
  [SMALL_STATE(7)] = 39,
  [SMALL_STATE(8)] = 52,
  [SMALL_STATE(9)] = 65,
  [SMALL_STATE(10)] = 69,
  [SMALL_STATE(11)] = 73,
  [SMALL_STATE(12)] = 77,
  [SMALL_STATE(13)] = 81,
  [SMALL_STATE(14)] = 85,
  [SMALL_STATE(15)] = 89,
  [SMALL_STATE(16)] = 93,
  [SMALL_STATE(17)] = 97,
  [SMALL_STATE(18)] = 101,
  [SMALL_STATE(19)] = 105,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_yellow_highlight, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_yellow_highlight, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_green_highlight, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_green_highlight, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_red_highlight, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_red_highlight, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blue_highlight, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blue_highlight, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_white_highlight, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_white_highlight, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [71] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_custom(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
